#!/usr/bin/env python3
"""Audit fixes for index.html — 13 項一次到位.
A1 序章「四個世代」→「十五種動態」
A2 Cluster 04 voice 改詞
A3 Footer credits 改中性版
B1 Google Fonts 加 Inter
B2 砍 --accent，只留 hue4 / accent-2
C1 Card <a> 沒 href → aria-disabled + cursor:default
C2 Cluster 標題 span → h2
C3 Card thumb alt 語義化
D1 40 PNG → WebP（另跑）
E2 Hero scroll cue 顯眼一點
"""
import re, os
from pathlib import Path

ROOT = Path("/Users/aqualux/Documents/Claude/Projects/全專案規劃/aqualux.dev/aqualux-design-spectrum")
HTML = ROOT / "index.html"

# 40 風格中文名（供 alt 文字用）
STYLES = {
    'c01': '玻璃擬態', 'c02': '新擬物化', 'c03': 'Material You', 'c04': '極簡主義', 'c05': '沉浸暗黑',
    'c06': '蒸氣波', 'c07': 'Y2K 千禧', 'c08': '90s Web 1.0', 'c09': '美式復古印刷', 'c10': '80s Synthwave', 'c11': '包浩斯',
    'c12': '野獸派', 'c13': '故障藝術', 'c14': '賽博龐克', 'c15': '構成主義', 'c16': 'ASCII 終端機', 'c17': '雜誌排版',
    'c18': '日式禪意', 'c19': '中國風國潮', 'c20': '北歐極簡', 'c21': '瑞士國際風格', 'c22': '台灣廟會',
    'c23': '等距 3D', 'c24': '手繪塗鴉', 'c25': '漸層 Mesh',
    'm26': '多層視差', 'm27': 'Sticky 堆疊章節', 'm28': '橫向滾動陣容',
    'm29': '全屏章節切換', 'm30': '滾動進度指示', 'm31': '滾動跑馬燈',
    'm32': '錯落淡入', 'm33': '打字機標題', 'm34': '數字爆裂計數',
    'm35': '極光漸層流動', 'm36': '漂浮幾何球', 'm37': '動態噪點',
    'm38': '滑鼠光暈', 'm39': '3D 傾斜卡片', 'm40': '磁吸按鈕',
}

html = HTML.read_text(encoding="utf-8")
changes = []

# A1: 「四個世代」→「十五種動態」
old = "四十種風格、四個世代、五個流派"
new = "四十種風格、五個流派、十五種動態"
if old in html:
    html = html.replace(old, new)
    changes.append(f"A1 序章: {old!r} → {new!r}")

# A2: Cluster 04 voice
old = "/ 文化暗號 · 跨境業務的護城河"
new = "/ 文化暗號 · 跨域識別的視覺護城河"
if old in html:
    html = html.replace(old, new)
    changes.append(f"A2 Cluster 04 voice")

# A3: Footer credits
old = "All 40 thumbnails are aqualux originals generated via gpt-image-2."
new = "Thumbnails generated by aqualux. Type set in Noto Serif TC + Cormorant Garamond + Inter."
if old in html:
    html = html.replace(old, new)
    changes.append(f"A3 Footer credits")

# B1: Add Inter to Google Fonts
old_link = 'family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500&family=JetBrains+Mono'
new_link = 'family=Cormorant+Garamond:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500&family=Inter:wght@300;400;500&family=JetBrains+Mono'
if old_link in html:
    html = html.replace(old_link, new_link)
    changes.append("B1 Inter font 加入 Google Fonts")

# B2: 砍 --accent，用 hue4 替換引用
# --accent: #5c7a9a 出現多次 — 暫時保留但註解為 legacy；先檢查使用點，hue4 / accent-2 已有使用
# 為了向下相容、改為 alias 而不是砍掉
old_var = "    --accent: #5c7a9a;"
new_var = "    --accent: #38a8ff;  /* alias of --hue4 (2026-05-19: 統一冷藍) */"
if old_var in html:
    html = html.replace(old_var, new_var)
    changes.append("B2 --accent 改 alias 為 --hue4 (#38a8ff)")

# C1: Card <a> 沒 href → aria-disabled (39 個 placeholder card)
# 抓 `<a><div class="card-thumb">` 沒 href → 改成 `<a aria-disabled="true" tabindex="-1" style="cursor:default;"><div class="card-thumb">`
pattern = re.compile(r'<article class="card"><a><div class="card-thumb">')
count = len(pattern.findall(html))
html = pattern.sub(
    '<article class="card"><a aria-disabled="true" tabindex="-1" data-status="placeholder"><div class="card-thumb">',
    html
)
if count > 0:
    changes.append(f"C1 {count} 個 placeholder card 加 aria-disabled + tabindex=-1")

# C2: Cluster .zh 從 <span> → <h2>; cluster-num <div> → <span>
# Pattern: <span class="zh">XXX</span> 在 .cluster-title 內 → <h2 class="zh">XXX</h2>
html = re.sub(
    r'(<div class="cluster-title">\s*)<span class="zh">([^<]+)</span>',
    r'\1<h2 class="zh">\2</h2>',
    html
)
changes.append("C2 Cluster .zh span → h2")

# 同步調整 CSS：原本 .cluster-title .zh 是 span，現在是 h2 — h2 預設有 margin 要 reset
# 找 `.cluster-title .zh {` 段、確認 margin:0 — 已用 flex-direction:column 不需要額外 margin reset
# (CSS already uses display:flex flex-direction:column on .cluster-title, h2 will respect it)

# C3: Card thumb alt 改為語義化
# Pattern: alt="C01 thumb" 等 → alt="{style_name} 風格示意圖"
def alt_replacer(m):
    slug = m.group(1).lower()
    name = STYLES.get(slug, f'C{slug[1:]}')
    return f'alt="{name} 風格示意圖"'
html = re.sub(r'alt="(C\d+) thumb"', alt_replacer, html)
# 但是 src=images/thumbs/cNN.png — 跟 alt 的 CNN 對應，我用 src 抓 slug 比較準
def alt_replacer_by_src(m):
    src = m.group(1)
    fname = os.path.basename(src).split('.')[0]  # 'c01' or 'm26'
    name = STYLES.get(fname, fname.upper())
    return f'<img src="{src}" loading="lazy" alt="{name} 風格示意圖">'
html = re.sub(
    r'<img src="(images/thumbs/[cm]\d+\.png)" loading="lazy" alt="[^"]+">',
    alt_replacer_by_src,
    html
)
changes.append("C3 40 張 thumb alt 改為「{風格名} 風格示意圖」")

# D1: PNG → WebP — 改 HTML 引用（實際轉換另跑 cwebp）
html = re.sub(
    r'src="images/thumbs/([cm]\d+)\.png"',
    r'src="images/thumbs/\1.webp"',
    html
)
changes.append("D1 HTML 引用 .png → .webp（檔案轉換另跑）")

# E2: Hero scroll cue 顯眼一點 — color 從 ink-3 提到 ink-2 + 加底線
old_cue_css = """  .scroll-cue {
    position: absolute; bottom: 32px; left: 50%; transform: translateX(-50%);
    font-family: var(--mono); font-size: 10.5px;
    color: var(--ink-3); letter-spacing: 0.3em;
    opacity: 0;
    animation: rise 1.6s 1.5s ease forwards, pulse 2.4s 2s ease-in-out infinite;
  }"""
new_cue_css = """  .scroll-cue {
    position: absolute; bottom: 28px; left: 50%; transform: translateX(-50%);
    font-family: var(--mono); font-size: 11.5px;
    color: var(--ink-2); letter-spacing: 0.32em;
    padding: 8px 16px;
    border: 1px solid var(--line);
    background: rgba(10,10,20,0.4);
    backdrop-filter: blur(8px); -webkit-backdrop-filter: blur(8px);
    opacity: 0;
    animation: rise 1.6s 1.5s ease forwards, pulse 2.4s 2s ease-in-out infinite;
  }"""
if old_cue_css in html:
    html = html.replace(old_cue_css, new_cue_css)
    changes.append("E2 Hero scroll-cue 加底線/背景框")

HTML.write_text(html, encoding="utf-8")

print("=" * 60)
print(f"✅ Audit fixes applied: {len(changes)} edits")
print("=" * 60)
for c in changes:
    print(f"  • {c}")
print()
print(f"File: {HTML} ({HTML.stat().st_size:,} bytes)")
